name: Push-to-EC2
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Build vendor files
      run: |
          composer install
          composer update

    - name: Build env file
      run: |
          cp .env.example .env
          php artisan key:generate

    - name: Build asset files
      run: |
          npm install
          npm run build

    - name: Copy files with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{secrets.REMOTE_HOST}}
        REMOTE_USER: ${{secrets.REMOTE_USER}}
        TARGET: ${{secrets.TARGET_DIR}}
        EXCLUDE: "/dist/, /node_modules/, /vendor/, /storage/, /bootstrap/, **.env, rebuild_app.sh, watcher.sh"